server:
  port: 9095

eureka:
  client:
    #registerWithEureka: true
    #fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: FOOD-CATALOGUE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/foodcataloguedb
    password: Arkssvv@2025
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
